<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Activity;

class ActivitySeeder extends Seeder
{
    public function run()
    {
        $activities = [
            ['type' => 'archery', 'name_en' => 'Archery', 'name_hu' => 'Íjászat', 'name_de' => 'Bogenschießen'],
            ['type' => 'badminton', 'name_en' => 'Badminton', 'name_hu' => 'Tollaslabda', 'name_de' => 'Badminton'],
            ['type' => 'barre', 'name_en' => 'Barre', 'name_hu' => 'Barre', 'name_de' => 'Barre'],
            ['type' => 'baseball', 'name_en' => 'Baseball', 'name_hu' => 'Baseball', 'name_de' => 'Baseball'],
            ['type' => 'basketball', 'name_en' => 'Basketball', 'name_hu' => 'Kosárlabda', 'name_de' => 'Basketball'],
            ['type' => 'biking', 'name_en' => 'Biking', 'name_hu' => 'Kerékpározás', 'name_de' => 'Radfahren'],
            ['type' => 'biking.stationary', 'name_en' => 'Biking stationary', 'name_hu' => 'Szobakerékpározás', 'name_de' => 'Heimtrainer'],
            ['type' => 'bootcamp', 'name_en' => 'Bootcamp', 'name_hu' => 'Bootcamp', 'name_de' => 'Bootcamp'],
            ['type' => 'bowling', 'name_en' => 'Bowling', 'name_hu' => 'Bowling', 'name_de' => 'Bowling'],
            ['type' => 'boxing', 'name_en' => 'Boxing', 'name_hu' => 'Ökölvívás', 'name_de' => 'Boxen'],
            ['type' => 'calisthenics', 'name_en' => 'Calisthenics', 'name_hu' => 'Saját testsúlyos edzés', 'name_de' => 'Eigengewichtstraining'],
            ['type' => 'cricket', 'name_en' => 'Cricket', 'name_hu' => 'Krikett', 'name_de' => 'Cricket'],
            ['type' => 'cooldown', 'name_en' => 'Cooldown', 'name_hu' => 'Levezetés', 'name_de' => 'Cool-down'],
            ['type' => 'core_training', 'name_en' => 'Core training', 'name_hu' => 'Törzserősítés', 'name_de' => 'Core-Training'],
            ['type' => 'crossfit', 'name_en' => 'Crossfit', 'name_hu' => 'Crossfit', 'name_de' => 'CrossFit'],
            ['type' => 'curling', 'name_en' => 'Curling', 'name_hu' => 'Curling', 'name_de' => 'Curling'],
            ['type' => 'dancing', 'name_en' => 'Dancing', 'name_hu' => 'Tánc', 'name_de' => 'Tanzen'],
            ['type' => 'dancing.social', 'name_en' => 'Social dancing', 'name_hu' => 'Társastánc', 'name_de' => 'Gesellschaftstanz'],
            ['type' => 'dancing.cardio', 'name_en' => 'Cardio dancing', 'name_hu' => 'Kardió tánc', 'name_de' => 'Cardio-Tanz'],
            ['type' => 'disc_sports', 'name_en' => 'Disc sports', 'name_hu' => 'Frizbi sportok', 'name_de' => 'Frisbee-Sport'],
            ['type' => 'elliptical', 'name_en' => 'Elliptical', 'name_hu' => 'Elliptikus tréner', 'name_de' => 'Crosstrainer'],
            ['type' => 'exercise_class', 'name_en' => 'Exercise class', 'name_hu' => 'Edzésóra', 'name_de' => 'Sportkurs'],
            ['type' => 'fencing', 'name_en' => 'Fencing', 'name_hu' => 'Vívás', 'name_de' => 'Fechten'],
            ['type' => 'fitness_gaming', 'name_en' => 'Fitness gaming', 'name_hu' => 'Fitness játék', 'name_de' => 'Fitness-Gaming'],
            ['type' => 'fishing', 'name_en' => 'Fishing', 'name_hu' => 'Horgászat', 'name_de' => 'Angeln'],
            ['type' => 'flexibility', 'name_en' => 'Flexibility', 'name_hu' => 'Nyújthatóság', 'name_de' => 'Beweglichkeit'],
            ['type' => 'football.american', 'name_en' => 'American football', 'name_hu' => 'Amerikai futball', 'name_de' => 'American Football'],
            ['type' => 'football.australian', 'name_en' => 'Australian football', 'name_hu' => 'Ausztrál futball', 'name_de' => 'Australian Football'],
            ['type' => 'football.soccer', 'name_en' => 'Soccer', 'name_hu' => 'Labdarúgás', 'name_de' => 'Fußball'],
            ['type' => 'frisbee_disc', 'name_en' => 'Frisbee disc', 'name_hu' => 'Frizbi', 'name_de' => 'Frisbee'],
            ['type' => 'golf', 'name_en' => 'Golf', 'name_hu' => 'Golf', 'name_de' => 'Golf'],
            ['type' => 'guided_breathing', 'name_en' => 'Guided breathing', 'name_hu' => 'Irányított légzés', 'name_de' => 'Geführte Atmung'],
            ['type' => 'gymnastics', 'name_en' => 'Gymnastics', 'name_hu' => 'Torna', 'name_de' => 'Gymnastik'],
            ['type' => 'handball', 'name_en' => 'Handball', 'name_hu' => 'Kézilabda', 'name_de' => 'Handball'],
            ['type' => 'interval_training.high_intensity', 'name_en' => 'High intensity interval training', 'name_hu' => 'Magas intenzitású intervallum edzés', 'name_de' => 'Hochintensives Intervalltraining'],
            ['type' => 'hiking', 'name_en' => 'Hiking', 'name_hu' => 'Túrázás', 'name_de' => 'Wandern'],
            ['type' => 'hockey', 'name_en' => 'Hockey', 'name_hu' => 'Jégkorong', 'name_de' => 'Eishockey'],
            ['type' => 'hockey.roller', 'name_en' => 'Roller hockey', 'name_hu' => 'Görkorcsolya hoki', 'name_de' => 'Inline-Hockey'],
            ['type' => 'horseback_riding', 'name_en' => 'Horseback riding', 'name_hu' => 'Lovaglás', 'name_de' => 'Reiten'],
            ['type' => 'hunting', 'name_en' => 'Hunting', 'name_hu' => 'Vadászat', 'name_de' => 'Jagen'],
            ['type' => 'ice_skating', 'name_en' => 'Ice skating', 'name_hu' => 'Jégkorcsolyázás', 'name_de' => 'Eislaufen'],
            ['type' => 'jump_rope', 'name_en' => 'Jump rope', 'name_hu' => 'Ugrókötél', 'name_de' => 'Seilspringen'],
            ['type' => 'kickboxing', 'name_en' => 'Kickboxing', 'name_hu' => 'Kick-box', 'name_de' => 'Kickboxen'],
            ['type' => 'lacrosse', 'name_en' => 'Lacrosse', 'name_hu' => 'Lacrosse', 'name_de' => 'Lacrosse'],
            ['type' => 'martial_arts', 'name_en' => 'Martial arts', 'name_hu' => 'Harcművészetek', 'name_de' => 'Kampfsport'],
            ['type' => 'meditation', 'name_en' => 'Meditation', 'name_hu' => 'Meditáció', 'name_de' => 'Meditation'],
            ['type' => 'mixed_metabolic_cardio', 'name_en' => 'Mixed metabolic cardio', 'name_hu' => 'Vegyes metabolikus kardió', 'name_de' => 'Gemischtes Stoffwechsel-Cardio'],
            ['type' => 'other', 'name_en' => 'Other', 'name_hu' => 'Egyéb', 'name_de' => 'Sonstiges'],
            ['type' => 'paddle_sports', 'name_en' => 'Paddle sports', 'name_hu' => 'Evezős sportok', 'name_de' => 'Paddelsport'],
            ['type' => 'paragliding', 'name_en' => 'Paragliding', 'name_hu' => 'Sárkányrepülés', 'name_de' => 'Gleitschirmfliegen'],
            ['type' => 'pilates', 'name_en' => 'Pilates', 'name_hu' => 'Pilates', 'name_de' => 'Pilates'],
            ['type' => 'play', 'name_en' => 'Play', 'name_hu' => 'Játék', 'name_de' => 'Spielen'],
            ['type' => 'pickleball', 'name_en' => 'Pickleball', 'name_hu' => 'Pickleball', 'name_de' => 'Pickleball'],
            ['type' => 'preparation_and_recovery', 'name_en' => 'Preparation and recovery', 'name_hu' => 'Előkészület és regeneráció', 'name_de' => 'Vorbereitung und Erholung'],
            ['type' => 'racquetball', 'name_en' => 'Racquetball', 'name_hu' => 'Racquetball', 'name_de' => 'Racquetball'],
            ['type' => 'rock_climbing', 'name_en' => 'Rock climbing', 'name_hu' => 'Sziklamászás', 'name_de' => 'Klettern'],
            ['type' => 'rowing', 'name_en' => 'Rowing', 'name_hu' => 'Evezés', 'name_de' => 'Rudern'],
            ['type' => 'rowing.machine', 'name_en' => 'Rowing machine', 'name_hu' => 'Evezőgép', 'name_de' => 'Rudergerät'],
            ['type' => 'rugby', 'name_en' => 'Rugby', 'name_hu' => 'Rögbi', 'name_de' => 'Rugby'],
            ['type' => 'running', 'name_en' => 'Running', 'name_hu' => 'Futás', 'name_de' => 'Laufen'],
            ['type' => 'running.treadmill', 'name_en' => 'Treadmill running', 'name_hu' => 'Futópad', 'name_de' => 'Laufband'],
            ['type' => 'sailing', 'name_en' => 'Sailing', 'name_hu' => 'Vitorlázás', 'name_de' => 'Segeln'],
            ['type' => 'scuba_diving', 'name_en' => 'Scuba diving', 'name_hu' => 'Búvárkodás', 'name_de' => 'Tauchen'],
            ['type' => 'skating', 'name_en' => 'Skating', 'name_hu' => 'Korcsolyázás', 'name_de' => 'Skating'],
            ['type' => 'skiing', 'name_en' => 'Skiing', 'name_hu' => 'Síelés', 'name_de' => 'Skifahren'],
            ['type' => 'skiing.cross_country', 'name_en' => 'Cross country skiing', 'name_hu' => 'Sífutás', 'name_de' => 'Skilanglauf'],
            ['type' => 'skiing.downhill', 'name_en' => 'Downhill skiing', 'name_hu' => 'Lesiklás', 'name_de' => 'Abfahrtski'],
            ['type' => 'snowboarding', 'name_en' => 'Snowboarding', 'name_hu' => 'Snowboard', 'name_de' => 'Snowboarden'],
            ['type' => 'snowshoeing', 'name_en' => 'Snowshoeing', 'name_hu' => 'Hótalpas túra', 'name_de' => 'Schneeschuhwandern'],
            ['type' => 'snow_sports', 'name_en' => 'Snow sports', 'name_hu' => 'Hósportok', 'name_de' => 'Schneesport'],
            ['type' => 'softball', 'name_en' => 'Softball', 'name_hu' => 'Softball', 'name_de' => 'Softball'],
            ['type' => 'squash', 'name_en' => 'Squash', 'name_hu' => 'Fallabda', 'name_de' => 'Squash'],
            ['type' => 'stair_climbing', 'name_en' => 'Stair climbing', 'name_hu' => 'Lépcsőzés', 'name_de' => 'Treppensteigen'],
            ['type' => 'stair_climbing.machine', 'name_en' => 'Stair climbing machine', 'name_hu' => 'Lépcsőzőgép', 'name_de' => 'Treppenstepper'],
            ['type' => 'strength_training', 'name_en' => 'Strength training', 'name_hu' => 'Erősítő edzés', 'name_de' => 'Krafttraining'],
            ['type' => 'strength_training.functional', 'name_en' => 'Functional strength training', 'name_hu' => 'Funkcionális erősítés', 'name_de' => 'Funktionelles Krafttraining'],
            ['type' => 'stretching', 'name_en' => 'Stretching', 'name_hu' => 'Nyújtás', 'name_de' => 'Dehnen'],
            ['type' => 'surfing', 'name_en' => 'Surfing', 'name_hu' => 'Szörfözés', 'name_de' => 'Surfen'],
            ['type' => 'swimming', 'name_en' => 'Swimming', 'name_hu' => 'Úszás', 'name_de' => 'Schwimmen'],
            ['type' => 'swimming.pool', 'name_en' => 'Pool swimming', 'name_hu' => 'Medence úszás', 'name_de' => 'Hallenschwimmen'],
            ['type' => 'swimming.open_water', 'name_en' => 'Open water swimming', 'name_hu' => 'Nyílt vízi úszás', 'name_de' => 'Freiwasserschwimmen'],
            ['type' => 'table_tennis', 'name_en' => 'Table tennis', 'name_hu' => 'Asztalitenisz', 'name_de' => 'Tischtennis'],
            ['type' => 'tai_chi', 'name_en' => 'Tai chi', 'name_hu' => 'Tai chi', 'name_de' => 'Tai-Chi'],
            ['type' => 'tennis', 'name_en' => 'Tennis', 'name_hu' => 'Tenisz', 'name_de' => 'Tennis'],
            ['type' => 'track_and_field', 'name_en' => 'Track and field', 'name_hu' => 'Atlétika', 'name_de' => 'Leichtathletik'],
            ['type' => 'volleyball', 'name_en' => 'Volleyball', 'name_hu' => 'Röplabda', 'name_de' => 'Volleyball'],
            ['type' => 'walking', 'name_en' => 'Walking', 'name_hu' => 'Gyaloglás', 'name_de' => 'Gehen'],
            ['type' => 'water_fitness', 'name_en' => 'Water fitness', 'name_hu' => 'Vízi fitnesz', 'name_de' => 'Aquafitness'],
            ['type' => 'water_polo', 'name_en' => 'Water polo', 'name_hu' => 'Vízilabda', 'name_de' => 'Wasserball'],
            ['type' => 'water_sports', 'name_en' => 'Water sports', 'name_hu' => 'Vízi sportok', 'name_de' => 'Wassersport'],
            ['type' => 'weightlifting', 'name_en' => 'Weightlifting', 'name_hu' => 'Súlyemelés', 'name_de' => 'Gewichtheben'],
            ['type' => 'wheelchair', 'name_en' => 'Wheelchair', 'name_hu' => 'Kerekesszékes', 'name_de' => 'Rollstuhl'],
            ['type' => 'wheelchair.walkpace', 'name_en' => 'Wheelchair walk pace', 'name_hu' => 'Kerekesszékes séta tempó', 'name_de' => 'Rollstuhl Gehgeschwindigkeit'],
            ['type' => 'wheelchair.runpace', 'name_en' => 'Wheelchair run pace', 'name_hu' => 'Kerekesszékes futás tempó', 'name_de' => 'Rollstuhl Laufgeschwindigkeit'],
            ['type' => 'wrestling', 'name_en' => 'Wrestling', 'name_hu' => 'Birkózás', 'name_de' => 'Ringen'],
            ['type' => 'yoga', 'name_en' => 'Yoga', 'name_hu' => 'Jóga', 'name_de' => 'Yoga'],
        ];

        foreach ($activities as $activity) {
            Activity::updateOrCreate(
                ['type' => $activity['type']],
                $activity
            );
        }
    }
}
